const topSongsByDecade = {
  '80s': [
    "Michael Jackson - Billie Jean",
    "Madonna - Like a Virgin",
    "Prince - When Doves Cry",
    "Whitney Houston - I Wanna Dance with Somebody",
    "Cyndi Lauper - Girls Just Want to Have Fun",
    "Bon Jovi - Livin' on a Prayer",
    "Guns N' Roses - Sweet Child o' Mine",
    "AC/DC - You Shook Me All Night Long",
    "Duran Duran - Hungry Like the Wolf",
    "Queen - Another One Bites the Dust",
    "U2 - With or Without You",
    "The Police - Every Breath You Take",
    "Journey - Don't Stop Believin'",
    "Toto - Africa",
    "Billy Joel - Uptown Girl",
    "George Michael - Faith",
    "The Clash - Should I Stay or Should I Go",
    "David Bowie - Let's Dance",
    "The Cure - Just Like Heaven",
    "Depeche Mode - Just Can't Get Enough",
    "Eurythmics - Sweet Dreams (Are Made of This)",
    "INXS - Need You Tonight",
    "Blondie - Call Me",
    "Rick Astley - Never Gonna Give You Up",
    "Van Halen - Jump",
    "Simple Minds - Don't You (Forget About Me)",
    "Europe - The Final Countdown",
    "A-ha - Take On Me",
    "Pet Shop Boys - West End Girls",
    "Michael Jackson - Thriller",
    "Bon Jovi - Wanted Dead or Alive",
    "Madonna - Material Girl",
    "Prince - Purple Rain",
    "Whitney Houston - How Will I Know",
    "Cyndi Lauper - Time After Time",
    "Survivor - Eye of the Tiger",
    "AC/DC - Back in Black",
    "Guns N' Roses - Welcome to the Jungle",
    "Queen - Radio Ga Ga",
    "U2 - Sunday Bloody Sunday",
    "The Police - Roxanne",
    "Journey - Faithfully",
    "Toto - Rosanna",
    "Billy Joel - We Didn't Start the Fire",
    "George Michael - Careless Whisper",
    "The Clash - London Calling",
    "David Bowie - Ashes to Ashes",
    "The Cure - Lovesong",
    "Depeche Mode - Enjoy the Silence",
    "Eurythmics - Here Comes the Rain Again",
    "INXS - New Sensation",
    "Blondie - Heart of Glass",
    "Rick Astley - Together Forever",
    "Van Halen - Panama",
    "Simple Minds - Alive and Kicking",
    "Europe - Carrie",
    "A-ha - The Sun Always Shines on T.V.",
    "Pet Shop Boys - It's a Sin",
    "Michael Jackson - Beat It",
    "Bon Jovi - You Give Love a Bad Name",
    "Madonna - Papa Don't Preach",
    "Prince - Kiss",
    "Whitney Houston - Saving All My Love for You",
    "Cyndi Lauper - True Colors",
    "Survivor - Burning Heart",
    "AC/DC - Highway to Hell",
    "Guns N' Roses - Paradise City",
    "Queen - Under Pressure",
    "U2 - I Still Haven't Found What I'm Looking For",
    "The Police - Message in a Bottle",
    "Journey - Separate Ways (Worlds Apart)",
    "Toto - Hold the Line",
    "Billy Joel - Piano Man",
    "George Michael - Father Figure",
    "The Clash - Rock the Casbah",
    "David Bowie - Modern Love",
    "The Cure - Boys Don't Cry",
    "Depeche Mode - Personal Jesus",
    "Eurythmics - Love Is a Stranger",
    "INXS - Never Tear Us Apart",
    "Blondie - Rapture",
    "Rick Astley - It Would Take a Strong Strong Man",
    "Van Halen - Why Can't This Be Love",
    "Simple Minds - Don't You Forget About Me",
    "Europe - Cherokee",
    "A-ha - Hunting High and Low",
    "Pet Shop Boys - Always on My Mind",
    "Michael Jackson - Smooth Criminal",
    "Bon Jovi - I'll Be There for You",
    "Madonna - Crazy for You",
    "Prince - Little Red Corvette",
    "Whitney Houston - Greatest Love of All",
    "Cyndi Lauper - She Bop",
    "Survivor - The Search Is Over",
    "AC/DC - Thunderstruck",
    "Guns N' Roses - Patience",
    "Queen - Crazy Little Thing Called Love",
    "U2 - Pride (In the Name of Love)",
    "The Police - Every Little Thing She Does Is Magic",
    "Journey - Open Arms",
    "Toto - I'll Be Over You",
    "Billy Joel - The Longest Time",
    "George Michael - One More Try",
    "The Clash - Train in Vain",
    "David Bowie - Heroes",
    "The Cure - Friday I'm in Love",
    "Depeche Mode - Policy of Truth",
    "Eurythmics - There Must Be an Angel (Playing with My Heart)",
    "INXS - Devil Inside",
    "Blondie - The Tide Is High",
    "Rick Astley - Whenever You Need Somebody",
    "Van Halen - Jump",
    "Simple Minds - Promised You a Miracle",
    "Europe - Rock the Night",
    "A-ha - Crying in the Rain",
    "Pet Shop Boys - Opportunities (Let's Make Lots of Money)",
    "Michael Jackson - Bad",
    "Bon Jovi - Wanted Dead or Alive",
    "Madonna - Into the Groove",
    "Prince - 1999",
    "Whitney Houston - How Will I Know",
    "Cyndi Lauper - All Through the Night",
    "Survivor - High on You",
    "AC/DC - Hells Bells",
    "Guns N' Roses - November Rain",
    "Queen - We Will Rock You",
    "U2 - Where the Streets Have No Name",
    "The Police - Don't Stand So Close to Me",
    "Journey - Wheel in the Sky",
    "Toto - Pamela",
    "Billy Joel - Just the Way You Are",
    "George Michael - Kissing a Fool",
    "The Clash - Should I Stay or Should I Go",
    "David Bowie - China Girl",
    "The Cure - In Between Days",
    "Depeche Mode - Strangelove",
    "Eurythmics - Who's That Girl?",
    "INXS - Suicide Blonde",
    "Blondie - Atomic",
    "Rick Astley - She Wants to Dance with Me",
    "Van Halen - Dreams",
    "Simple Minds - Sanctify Yourself",
    "Europe - The Final Countdown",
    "A-ha - Manhattan Skyline",
    "Pet Shop Boys - Domino Dancing",
    "Michael Jackson - The Way You Make Me Feel",
    "Bon Jovi - Lay Your Hands on Me",
    "Madonna - Like a Prayer",
    "Prince - Sign o' the Times",
    "Whitney Houston - So Emotional",
    "Cyndi Lauper - Money Changes Everything",
    "Survivor - Is This Love",
    "AC/DC - Shoot to Thrill",
    "Guns N' Roses - Don't Cry",
    "Queen - Bohemian Rhapsody",
    "U2 - With or Without You",
    "The Police - Every Breath You Take",
    "Journey - Any Way You Want It",
    "Toto - Stop Loving You",
    "Billy Joel - My Life",
    "George Michael - I Want Your Sex",
    "The Clash - Rock the Casbah",
    "David Bowie - Let's Dance",
    "The Cure - Close to Me",
    "Depeche Mode - Never Let Me Down Again",
    "Eurythmics - Sweet Dreams (Are Made of This)",
    "INXS - New Sensation",
    "Blondie - Heart of Glass",
    "Rick Astley - Together Forever",
    "Van Halen - When It's Love",
    "Simple Minds - Alive and Kicking",
    "Europe - Carrie",
    "A-ha - The Living Daylights",
    "Pet Shop Boys - Always on My Mind",
    "Michael Jackson - Smooth Criminal",
    "Bon Jovi - Bad Medicine",
    "Madonna - Express Yourself",
    "Prince - Batdance",
    "Whitney Houston - I'm Your Baby Tonight",
    "Cyndi Lauper - Change of Heart",
    "Survivor - Burning Heart",
    "AC/DC - Back in Black",
    "Guns N' Roses - Paradise City",
    "Queen - Under Pressure",
    "U2 - I Still Haven't Found What I'm Looking For",
    "The Police - Message in a Bottle",
    "Journey - Separate Ways (Worlds Apart)",
    "Toto - Hold the Line",
    "Billy Joel - Piano Man",
    "George Michael - Father Figure",
    "The Clash - Rock the Casbah",
    "David Bowie - Modern Love",
    "The Cure - Boys Don't Cry",
    "Depeche Mode - Personal Jesus",
    "Eurythmics - Love Is a Stranger",
    "INXS - Never Tear Us Apart",
    "Blondie - Rapture",
    "Rick Astley - It Would Take a Strong Strong Man",
    "Van Halen - Why Can't This Be Love",
    "Simple Minds - Don't You Forget About Me",
  ],
  '90s': [
      "Nirvana - Smells Like Teen Spirit",
      "Backstreet Boys - I Want It That Way",
      "Britney Spears - ...Baby One More Time",
      "TLC - Waterfalls",
      "Spice Girls - Wannabe",
      // Add more 90s songs...
  ],
  '2000s': [
      "Eminem - Lose Yourself",
      "Beyoncé - Crazy in Love",
      "Outkast - Hey Ya!",
      "Usher - Yeah!",
      "Green Day - Boulevard of Broken Dreams",
      // Add more 2000s songs...
  ],
  '2010s': [
      "Gotye - Somebody That I Used to Know",
      "Lorde - Royals",
      "Pharrell Williams - Happy",
      "Adele - Rolling in the Deep",
      "Ed Sheeran - Shape of You",
      // Add more 2010s songs...
  ],
  '2020s': [
      "The Weeknd - Blinding Lights",
      "BTS - Dynamite",
      "Dua Lipa - Don't Start Now",
      "Cardi B - WAP",
      "Billie Eilish - Bad Guy",
      // Add more 2020s songs...
  ],
  'Rock': [
      "Queen - Bohemian Rhapsody",
      "Led Zeppelin - Stairway to Heaven",
      "The Rolling Stones - (I Can't Get No) Satisfaction",
      "Pink Floyd - Comfortably Numb",
      "The Beatles - Hey Jude",
      // Add more Rock songs...
  ],
  'Pop': [
      "Michael Jackson - Thriller",
      "Elton John - Candle in the Wind",
      "Whitney Houston - I Will Always Love You",
      "ABBA - Dancing Queen",
      "Justin Timberlake - Cry Me a River",
      // Add more Pop songs...
  ],
  'Hip Hop': [
      "Tupac - California Love",
      "The Notorious B.I.G. - Juicy",
      "Jay-Z - Empire State of Mind",
      "Eminem - Stan",
      "Kanye West - Gold Digger",
      // Add more Hip Hop songs...
  ],
  'R&B': [
      "Marvin Gaye - Sexual Healing",
      "Aretha Franklin - Respect",
      "Stevie Wonder - Superstition",
      "Beyoncé - Halo",
      "Rihanna - Umbrella",
      // Add more R&B songs...
  ],
  'Country': [
      "Johnny Cash - Ring of Fire",
      "Dolly Parton - Jolene",
      "Willie Nelson - On the Road Again",
      "Shania Twain - Man! I Feel Like a Woman!",
      "Taylor Swift - Love Story",
      // Add more Country songs...
  ],
  'Eletrônica': [
      "Daft Punk - Around the World",
      "Calvin Harris - This Is What You Came For",
      "The Chemical Brothers - Block Rockin' Beats",
      "David Guetta - Titanium",
      "Skrillex - Bangarang",
      // Add more Eletrônica songs...
  ],
  'Jazz': [
      "Miles Davis - So What",
      "John Coltrane - Giant Steps",
      "Ella Fitzgerald - Summertime",
      "Louis Armstrong - What a Wonderful World",
      "Nina Simone - Feeling Good",
      // Add more Jazz songs...
  ],
  'Clássica': [
      "Ludwig van Beethoven - Symphony No. 9",
      "Johann Sebastian Bach - Toccata and Fugue in D Minor",
      "Wolfgang Amadeus Mozart - Requiem",
      "Pyotr Ilyich Tchaikovsky - Swan Lake",
      "Antonio Vivaldi - The Four Seasons",
      // Add more Clássica songs...
  ],
  'Reggae': [
      "Bob Marley - No Woman, No Cry",
      "Jimmy Cliff - Many Rivers to Cross",
      "Toots and the Maytals - Pressure Drop",
      "Peter Tosh - Legalize It",
      "UB40 - Red Red Wine",
      // Add more Reggae songs...
  ],
  'Samba': [
      "Cartola - As Rosas Não Falam",
      "Clara Nunes - A Deusa dos Orixás",
      "Paulinho da Viola - Foi um Rio que Passou em Minha Vida",
      "Beth Carvalho - Coisinha do Pai",
      "Zeca Pagodinho - Deixa a Vida Me Levar",
      // Add more Samba songs...
  ],
  'Bossa Nova': [
      "João Gilberto - Chega de Saudade",
      "Tom Jobim - Garota de Ipanema",
      "Vinícius de Moraes - Desafinado",
      "Elis Regina - Águas de Março",
      "Caetano Veloso - Samba de Verão",
      // Add more Bossa Nova songs...
  ],
  'Forró': [
      "Luiz Gonzaga - Asa Branca",
      "Dominguinhos - Isso Aqui Tá Bom Demais",
      "Elba Ramalho - De Volta Pro Aconchego",
      "Alceu Valença - Anjo Avesso",
      "Falamansa - Xote dos Milagres",
      // Add more Forró songs...
  ],
  'Funk Carioca': [
      "MC Marcinho - Rap do Solitário",
      "Claudinho & Buchecha - Quero Te Encontrar",
      "Anitta - Show das Poderosas",
      "MC Kevinho - Olha a Explosão",
      "Ludmilla - Verdinha",
      // Add more Funk Carioca songs...
  ],
  'Axé': [
      "Ivete Sangalo - Festa",
      "Daniela Mercury - O Canto da Cidade",
      "Banda Eva - Beleza Rara",
      "Chiclete com Banana - Voa Voa",
      "Asa de Águia - Dia dos Namorados",
      // Add more Axé songs...
  ],
  'Sertanejo 80s': [
      "Chitãozinho & Xororó - Fio de Cabelo",
      "Leandro & Leonardo - Pense em Mim",
      "Gian & Giovani - Nem Dormindo Consigo te Esquecer",
      "Rio Negro & Solimões - De São Paulo a Belém",
      "João Paulo & Daniel - Estou Apaixonado",
      // Add more Sertanejo 80s songs...
  ],
  'Sertanejo 90s': [
      "Zezé Di Camargo & Luciano - É o Amor",
      "Daniel - Adoro Amar Você",
      "Chrystian & Ralf - Nova York",
      "Leandro & Leonardo - Sonho Por Sonho",
      "João Paulo & Daniel - Só Dá Você na Minha Vida",
      // Add more Sertanejo 90s songs...
  ],
  'Frevo': [
      "Alceu Valença - Frevo Mulher",
      "Antônio Nóbrega - Vassourinhas",
      "Spok Frevo Orquestra - Aconteceu",
      "Fafá de Belém - Último Regresso",
      "Lenine - O Último Pôr do Sol",
      // Add more Frevo songs...
  ],
  'Forró Pé de Serra': [
      "Jackson do Pandeiro - Sebastiana",
      "Luiz Gonzaga - Baião",
      "Dominguinhos - De Volta Pro Aconchego",
      "Elba Ramalho - Anjo Avesso",
      "Falamansa - Xote dos Milagres",
      // Add more Forró Pé de Serra songs...
  ],
  'Surpresa': [
      // Surprise songs...
  ],
};

function selectRandomSong(genre) {
  const songs = topSongsByDecade[genre];
  if (!songs || songs.length === 0) {
      alert('Nenhuma música disponível para este gênero');
      return;
  }

  // Randomly select a song index
  const randomIndex = Math.floor(Math.random() * songs.length);
  const selectedSong = songs[randomIndex];

  // Display the selected song
  document.getElementById('selectedSong').innerHTML = `<div>${selectedSong}</div>`;

  // Show loading spinner
  document.getElementById('loading').style.display = 'block';

  // Open a new window with YouTube search for the selected song + karaoke after 3 seconds
  setTimeout(() => {
      const searchQuery = encodeURIComponent(selectedSong + ' karaoke');
      window.open('https://www.youtube.com/results?search_query=' + searchQuery);
      // Hide loading spinner after opening the YouTube search
      document.getElementById('loading').style.display = 'none';
  }, 3000);
}
